### ISSUE TITLE
Feature Request:  Choose whether to sort to top or bottom

### ISSUE THREAD

**Issue by robross0606** [Erl-koenig/obsidian-checkboxReorder#10]
It isn't always desirable to move checked items to the bottom.  Would be great if you could introduce a plugin option to sort them at the top instead.

**Comment by Erl-koenig** [comment]
@robross0606 I've added an option in the settings to choose if you wanna sort it to the top or bottom. Was this the request, or was it to have two separate commands (one for top sorting and one for bottom sorting)?

**Comment by robross0606** [comment]
What you did is precisely what I was asking for.  Thank you!
