### ISSUE TITLE
Children should move along with their parents 👩‍👧‍👦

### ISSUE THREAD

**Issue by lukemt** [Erl-koenig/obsidian-checkboxReorder#4]
After reordering the to-do items, nested lists should be rearranged correctly, moving along with their parents. Consider the following Markdown:

```markdown
- [x] Top-level task 1
  - [ ] Subtask 1
  - [ ] Subtask 2
- [ ] Top-level task 2
- [x] Top-level task 3
```

Should be rearranged to this:

```markdown
- [ ] Top-level task 2
- [x] Top-level task 1
  - [ ] Subtask 1
  - [ ] Subtask 2
- [x] Top-level task 3
```

**Comment by lukemt** [comment]
I have already implemented this just not yet made a commit or pull request. It won't reorder subtasks though which is a another feature one could imagine

**Comment by Erl-koenig** [comment]
@lukemt Hi Luke, I've reviewed your commits and tested. It works really well. I'll create a new release with all the changes soon. Thanks for your effort! If it's fine for you, I can mention / add your github profile link in the documentation.

**Comment by lukemt** [comment]
Hi @Erl-koenig 

Glad to hear this.

Sure, it would be an honor

**Comment by lukemt** [comment]
also shipped 🍾
